import { NextResponse } from 'next/server';
import { GoogleGenAI, Type } from '@google/genai';
import { DEFAULT_TRIP_PLACES } from '@/features/trips/constants/default-places';
import {
  BASECAMP_TO_EVENT_POOL,
  EVENT_CATALOG,
  type ConciergeEvent,
  type EventPoolKey
} from '@/features/trips/constants/concierge-events';

const DEFAULT_GEMINI_MODEL = process.env.GEMINI_MODEL || 'gemini-2.5-flash';

const GENERATED_TRIP_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    name: { type: Type.STRING },
    summary: { type: Type.STRING },
    itinerary: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          event_id: { type: Type.STRING },
          day: { type: Type.STRING },
          date: { type: Type.STRING },
          startTime: { type: Type.STRING },
          endTime: { type: Type.STRING }
        },
        required: ['event_id', 'day', 'date', 'startTime', 'endTime']
      }
    }
  },
  required: ['name', 'summary', 'itinerary']
};

type GenerateRequestBody = {
  preferences: Record<string, string[]>;
  notes?: string;
};

type GeneratedItineraryItem = {
  event_id: string;
  day: string;
  date: string;
  startTime: string;
  endTime: string;
};

type GeneratedTrip = {
  name: string;
  summary: string;
  itinerary: GeneratedItineraryItem[];
};

const TRIP_TAGGED_IMAGE_POOL = Array.from(
  new Set(DEFAULT_TRIP_PLACES.map((place) => place.image).filter(Boolean))
);

function getRandomTripImage(fallback: string): string {
  if (TRIP_TAGGED_IMAGE_POOL.length === 0) {
    return fallback;
  }

  const randomIndex = Math.floor(Math.random() * TRIP_TAGGED_IMAGE_POOL.length);
  return TRIP_TAGGED_IMAGE_POOL[randomIndex] || fallback;
}

function clampWords(value: string, maxWords: number): string {
  const words = value.trim().split(/\s+/).filter(Boolean);

  if (words.length === 0) {
    return 'Personalized itinerary generated by Gemini concierge.';
  }

  if (words.length <= maxWords) {
    return words.join(' ');
  }

  return words.slice(0, maxWords).join(' ');
}

function sanitizeDay(value: string | undefined, fallback: string): string {
  const allowedDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  if (!value) return fallback;
  return allowedDays.includes(value) ? value : fallback;
}

function sanitizeDate(value: string | undefined, fallback: string): string {
  if (!value) return fallback;
  const isValid = /^\d{4}-\d{2}-\d{2}$/.test(value);
  return isValid ? value : fallback;
}

function sanitizeTime(value: string | undefined, fallback: string): string {
  if (!value) return fallback;
  const isValid = /^([01]\d|2[0-3]):[0-5]\d$/.test(value);
  return isValid ? value : fallback;
}

function timeToMinutes(value: string): number {
  const [hours, minutes] = value.split(':').map((segment) => Number(segment));
  return hours * 60 + minutes;
}

function ensureTimeRange(startTime: string, endTime: string) {
  if (timeToMinutes(endTime) > timeToMinutes(startTime)) {
    return { startTime, endTime };
  }

  const shiftedEnd = timeToMinutes(startTime) + 90;
  const hours = Math.floor((shiftedEnd % (24 * 60)) / 60)
    .toString()
    .padStart(2, '0');
  const minutes = (shiftedEnd % 60).toString().padStart(2, '0');

  return {
    startTime,
    endTime: `${hours}:${minutes}`
  };
}

function createFutureDate(baseDate: Date, offsetDays: number): string {
  const nextDate = new Date(baseDate);
  nextDate.setDate(nextDate.getDate() + offsetDays);
  return nextDate.toISOString().slice(0, 10);
}

function getPoolKey(preferences: Record<string, string[]>): EventPoolKey {
  const selectedBasecamp = preferences['logistics_basecamp']?.[0] || 'Kuriftu Bishoftu';
  return (BASECAMP_TO_EVENT_POOL[selectedBasecamp as keyof typeof BASECAMP_TO_EVENT_POOL] ||
    'Kuriftu_Bishoftu') as EventPoolKey;
}

function getAnchor(poolKey: EventPoolKey) {
  if (poolKey === 'Kuriftu_Awash_Falls') {
    return DEFAULT_TRIP_PLACES.find((place) => place.name === 'Kuriftu Resort & Spa Adama');
  }

  if (poolKey === 'Kuriftu_Bahir_Dar') {
    return DEFAULT_TRIP_PLACES.find((place) => place.name === 'Kuriftu Resort & Spa Bahir Dar');
  }

  if (poolKey === 'Kuriftu_Entoto_Adventure_Park') {
    return DEFAULT_TRIP_PLACES.find((place) => place.name === 'Skylight In-Terminal Hotel');
  }

  return DEFAULT_TRIP_PLACES.find((place) => place.name === 'Kuriftu Resort & Spa Bishoftu');
}

const TIME_SLOTS = [
  { startTime: '09:00', endTime: '11:30' },
  { startTime: '12:30', endTime: '14:30' },
  { startTime: '15:30', endTime: '17:30' },
  { startTime: '18:30', endTime: '20:30' }
];

const DAYS_ORDER = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

function generateFallbackItinerary(
  pool: ConciergeEvent[],
  anchor: (typeof DEFAULT_TRIP_PLACES)[0],
  preferences: Record<string, string[]>,
  tripCreationDate: Date
) {
  const goal = preferences['interests_goal']?.[0] || 'Relaxation';
  const pace = preferences['interests_pace']?.[0] || 'Balanced';
  const count = pace === 'Relaxed & slow' ? 4 : pace === 'Fast-paced / packed' ? 6 : 5;

  const goalLower = goal.toLowerCase();
  const sortedPool = [...pool].sort((a, b) => {
    const aMatch =
      a.category.toLowerCase().includes(goalLower) ||
      a.title.toLowerCase().includes(goalLower) ||
      a.description.toLowerCase().includes(goalLower);
    const bMatch =
      b.category.toLowerCase().includes(goalLower) ||
      b.title.toLowerCase().includes(goalLower) ||
      b.description.toLowerCase().includes(goalLower);
    if (aMatch && !bMatch) return -1;
    if (!aMatch && bMatch) return 1;
    return 0;
  });

  const selectedEvents = sortedPool.slice(0, Math.min(count, sortedPool.length));

  return selectedEvents.map((event, index) => {
    const dayOffset = Math.floor(index / 2);
    const slot = TIME_SLOTS[index % TIME_SLOTS.length];
    const lngOffset = ((index % 3) - 1) * 0.008;
    const latOffset = (Math.floor(index / 3) % 3) * 0.006;
    const dayName = DAYS_ORDER[(tripCreationDate.getDay() + dayOffset) % 7] || 'Mon';

    return {
      name: event.title,
      city: anchor.city,
      category: event.category,
      lng: Number((anchor.lng + lngOffset).toFixed(6)),
      lat: Number((anchor.lat + latOffset).toFixed(6)),
      image: getRandomTripImage(anchor.image),
      day: dayName,
      date: createFutureDate(tripCreationDate, dayOffset),
      startTime: slot.startTime,
      endTime: slot.endTime,
      loyaltyPoints: event.reward
    };
  });
}

export async function POST(request: Request) {
  try {
    const apiKey =
      process.env.GEMINI_API_KEY ||
      process.env.GOOGLE_GENAI_API_KEY ||
      process.env.GOOGLE_API_KEY ||
      '';

    const body = (await request.json()) as GenerateRequestBody;
    const preferences = body.preferences ?? {};
    const notes = body.notes?.trim() ?? '';
    const poolKey = getPoolKey(preferences);
    const pool = EVENT_CATALOG[poolKey] || EVENT_CATALOG.Kuriftu_Bishoftu;
    const anchor = getAnchor(poolKey) ?? DEFAULT_TRIP_PLACES[0];
    const tripCreationDate = new Date();

    let generatedTrip: GeneratedTrip | null = null;

    if (apiKey) {
      try {
        const ai = new GoogleGenAI({ apiKey });

        const prompt = `You are a luxury travel concierge for Kuriftu Resort and Spa.
Guest preferences: ${JSON.stringify(preferences)}
Additional guest notes: ${notes || 'None'}

Selected resort basecamp: ${poolKey}

Choose event_id values strictly from this catalog:
${JSON.stringify(pool)}

Requirements:
- Return a 1 to 3 day itinerary.
- Select 4 to 6 events with event_id matching the allowed list.
- Use 3-letter day labels: Mon, Tue, Wed, Thu, Fri, Sat, Sun.
- Use YYYY-MM-DD for date and HH:mm (24h) for startTime and endTime.
- Output JSON strictly matching the response schema.`;

        const response = await ai.models.generateContent({
          model: DEFAULT_GEMINI_MODEL,
          contents: prompt,
          config: {
            responseMimeType: 'application/json',
            responseSchema: GENERATED_TRIP_SCHEMA
          }
        });

        let rawText = response.text || '';
        rawText = rawText
          .replace(/^```json\s*/i, '')
          .replace(/^```\s*/i, '')
          .replace(/```\s*$/i, '')
          .trim();

        if (rawText) {
          generatedTrip = JSON.parse(rawText) as GeneratedTrip;
        }
      } catch (geminiError) {
        console.warn(
          'Gemini API call failed, falling back to smart concierge planner:',
          geminiError
        );
      }
    } else {
      console.info('No GEMINI_API_KEY found on environment. Using smart concierge planner.');
    }

    const goal = preferences['interests_goal']?.[0] || 'Experience';
    const resortName = poolKey.replace(/_/g, ' ');

    let places = DEFAULT_TRIP_PLACES.slice(0, 4);
    let tripName = `${resortName} ${goal} Journey`;
    let tripSummary = `Curated ${resortName} itinerary tailored for ${goal.toLowerCase()}.`;

    if (
      generatedTrip &&
      Array.isArray(generatedTrip.itinerary) &&
      generatedTrip.itinerary.length > 0
    ) {
      const byId = pool.reduce<Record<string, ConciergeEvent>>((accumulator, event) => {
        accumulator[event.id] = event;
        return accumulator;
      }, {});

      places = generatedTrip.itinerary.map((item, index) => {
        const fallbackEvent = pool[index % pool.length];
        const selectedEvent = byId[item.event_id] ?? fallbackEvent;
        const lngOffset = ((index % 3) - 1) * 0.008;
        const latOffset = (Math.floor(index / 3) % 3) * 0.006;
        const safeStart = sanitizeTime(item.startTime, anchor.startTime);
        const safeEnd = sanitizeTime(item.endTime, anchor.endTime);
        const range = ensureTimeRange(safeStart, safeEnd);
        const dayOffset = Math.floor(index / 2);
        const safeDate = sanitizeDate(item.date, createFutureDate(tripCreationDate, dayOffset));

        return {
          name: selectedEvent.title,
          city: anchor.city,
          category: selectedEvent.category,
          lng: Number((anchor.lng + lngOffset).toFixed(6)),
          lat: Number((anchor.lat + latOffset).toFixed(6)),
          image: getRandomTripImage(anchor.image),
          day: sanitizeDay(item.day, anchor.day),
          date: safeDate,
          startTime: range.startTime,
          endTime: range.endTime,
          loyaltyPoints: selectedEvent.reward
        };
      });

      if (generatedTrip.name) tripName = generatedTrip.name;
      if (generatedTrip.summary) tripSummary = clampWords(generatedTrip.summary, 20);
    } else {
      places = generateFallbackItinerary(pool, anchor, preferences, tripCreationDate);
    }

    return NextResponse.json({
      name: tripName,
      summary: tripSummary,
      places
    });
  } catch (error) {
    console.error('Failed to generate trip:', error);
    return NextResponse.json(
      { error: 'Failed to generate itinerary. Please try again.' },
      { status: 500 }
    );
  }
}
